### ISSUE TITLE
Include language of file on dashboard?

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#111]
Now that files only have one language, it might be useful to display this language on the user dashboard (similarly as https://ideone.com/myrecent). Would need to modify the following files:

https://github.com/cpinitiative/ide/blob/7264991fcc40fbdb28ed237266bc7eccc890cd50/src/hooks/useUpdateUserDashboard.ts#L50

https://github.com/cpinitiative/ide/blob/2975b6f0018d08cbaa29a7c24f7f6ee0c9dc0edb/src/components/Dashboard/FilesList.tsx#L9

**Comment by tarunsamanta2k20** [comment]
What would be the new parameter in type file and useUpdateDashboard?

**Comment by bqi343** [comment]
the language of the file is in `settings.language`

**Comment by tarunsamanta2k20** [comment]
May i work on it?

**Comment by bqi343** [comment]
sure

**Comment by shaubby** [comment]
@bqi343 did this ever get fixed or should i work on it

**Comment by bqi343** [comment]
feel free to work on it

**Comment by shaubby** [comment]
@bqi343 im struggling to figure out how to access the language of the file. It looks like FilesList.tsx contains a definition for a File object. It also seems like the firebase database contains a list of file objects for each user. And in Dashboard.tsx it retrieves the data from the objects in lines 57-78. This returns a number of values but not the language of the file (possibly because of the transition from the old ide, where a file could change languages?). Therefore, we either need to update the database itself to include the language for each file in the users file list, or find a new way to retrieve the language of the file. It is difficult for me to figure out what to do because I do not know how the database is laid out since I do not have access.

**Comment by bqi343** [comment]
#112 does this already, all that remains is to display the language

<img width="1243" alt="Screen Shot 2023-07-10 at 11 19 23 PM" src="https://github.com/cpinitiative/ide/assets/21228024/9a537337-dd44-42ae-9504-12f0696321aa">
